# Generated by Django 5.1.5 on 2025-01-31 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('cpf', models.CharField(max_length=9, unique=True)),
                ('senha', models.CharField(max_length=9)),
                ('saldo', models.FloatField()),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=512, unique=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.contabancaria')),
            ],
        ),
    ]
